//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokémons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrenadores
    {
        public string Id_Entrenador { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Pueblo { get; set; }
        public string Pokemons { get; set; }
        public Nullable<int> Num_Medallas { get; set; }
        public string Nom_Medallas { get; set; }
    
        public virtual Pokemon Pokemon { get; set; }
    }
}
